services:
  mysql-shopping-cart-sd:
    image: 'mysql:8.4.3'
    environment:
      - 'MYSQL_DATABASE=shopping-cart-sd'
      - 'MYSQL_ROOT_PASSWORD=12345'
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql
volumes:
  dbdata:
