package com.orrot.store.shoppingcart.adapter.input.model;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

public record CartView(
        @Schema(description = "Generated by the system", accessMode = Schema.AccessMode.READ_ONLY) Long id,
        PaymentMethodView payment,
        Long associatedUserId,
        List<CartItemView> items) {

}
