package com.orrot.store.shoppingcart.adapter.output;

import com.orrot.store.shoppingcart.adapter.output.jpa.CartJpaRepository;
import com.orrot.store.shoppingcart.adapter.output.jpa.mapper.CartDomainMapper;
import com.orrot.store.shoppingcart.domain.exception.DomainSavingException;
import com.orrot.store.shoppingcart.domain.model.Cart;
import com.orrot.store.shoppingcart.port.output.CartOutputPort;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;
import org.springframework.validation.annotation.Validated;

import java.util.Optional;

@Repository
@Transactional
@RequiredArgsConstructor
@Validated
public class CartRepository implements CartOutputPort {

    private final CartJpaRepository cartJpaRepository;
    private final CartDomainMapper cartDomainMapper;

    @Override
    public Cart create(@NotNull @Valid Cart cartToCreate) {
        return Optional.of(cartToCreate)
                .filter(newCart -> newCart.getId() == null)
                .map(cartDomainMapper::mapToJpaEntity)
                .map(cartJpaRepository::save)
                .map(cartDomainMapper::mapToDomain)
                .orElseThrow(() -> new DomainSavingException("The cart ID must be null to create a new cart because is autogenerated"));
    }

    @Override
    public Cart update(@NotNull @Valid Cart cartToUpdate) {
        return Optional.of(cartToUpdate)
                .map(Cart::getId)
                .map(cartJpaRepository::findById)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .map(existingCartEntity -> cartDomainMapper.mapToExistingEntity(cartToUpdate, existingCartEntity))
                .map(cartJpaRepository::save)
                .map(cartDomainMapper::mapToDomain)
                .orElseThrow(() -> new DomainSavingException(
                        "ID is not valid. The cart should contain a non-null existing id to be updated"));
    }

    @Override
    public Optional<Cart> findById(Long cartId) {
        return cartJpaRepository.findById(cartId)
                .map(cartDomainMapper::mapToDomain);
    }
}
